name: Deploy Application

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때만 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Remote Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
           script:
               cd /usr/share/moiem-backend && git pull origin main
               cd /usr/share/moiem-backend && npm install
               # npm run build (필요 시)
               pm2 restart moiem-backend  # PM2 앱 이름이 맞는지 확인하세요
