name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH Remote Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # NVM을 초기화하고 실행하도록 수정
          script: |
              cd /usr/share/moiem-backend
              git pull origin main
              
              # NVM 환경 로드
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm use 24.18.0
              
              npm install
              npm run build
              
              # 프로세스가 있으면 restart, 없으면 start
              pm2 describe moiem-backend > /dev/null
              if [ $? -eq 0 ]; then
                pm2 restart moiem-backend
              else
                pm2 start dist/main.js --name moiem-backend
              fi
